import type { Metadata } from "next";
import "./globals.css";

import { Link } from "@/catalyst/link";
import {
  Sidebar,
  SidebarBody,
  SidebarHeader,
  SidebarHeading,
  SidebarItem,
  SidebarLabel,
  SidebarSection,
} from "@/catalyst/sidebar";
import { SidebarLayout } from "@/catalyst/sidebar-layout";
import {
  Navbar,
  NavbarDivider,
  NavbarItem,
  NavbarSection,
  NavbarSpacer,
} from "@/catalyst/navbar";

export const metadata: Metadata = {
  title: "Entain Power User",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch(
    "https://api.tab.co.nz/gql/router?variables=%7B%22marketControlExclude%22%3Afalse%7D&operationName=SportingCategories&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%2215fe182fc110ba95c04a688ae603f3f70553fa412295d2cc1114fca5f6aec4f1%22%7D%7D",
    {
      headers: {
        accept: "application/graphql-response+json, application/json",
        "accept-language": "en-GB,en-US;q=0.9,en;q=0.8",
        "cache-control": "no-cache",
        "content-type": "application/json",
        "graphql-client-build": "e7f6319ee7859d7c5328f9cb2fe26a585ad574a9",
        "graphql-client-name": "sportsbook",
        "graphql-client-version": "hotfix/disable-last-5-request-invalid-uuid",
        pragma: "no-cache",
        priority: "u=1, i",
        "sec-ch-ua":
          '"Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"macOS"',
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-site",
        Referer: "https://www.tab.co.nz/",
      },
      body: null,
      method: "GET",
    }
  );

  type MarketResponse = {
    data: {
      categories: [
        {
          id: string;
          name: string;
          slug: string;
          url: string;
        }
      ];
    };
  };

  const json: MarketResponse = await res.json();

  const repo = "https://github.com/carlaiau/entain-power-user";
  const shit = "https://shitodds.com";
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <SidebarLayout
          navbar={
            <Navbar>
              <NavbarSection>
                <NavbarItem href="/statement" to="/statement">
                  Statement Fetcher
                </NavbarItem>
              </NavbarSection>
              <NavbarDivider />
              <NavbarSection>
                <NavbarItem to={shit} href={shit}>
                  Shit Odds
                </NavbarItem>
                <NavbarItem to={repo} href={repo}>
                  Github
                </NavbarItem>
              </NavbarSection>
            </Navbar>
          }
          sidebar={
            <Sidebar>
              <SidebarHeader className="text-lg font-semibold tracking-tight">
                <SidebarSection className="max-lg:hidden">
                  <SidebarHeading>Entain</SidebarHeading>
                  <SidebarItem href="/transaction" to="/transaction">
                    Transaction Fetcher
                  </SidebarItem>
                  <SidebarItem href="/statement" to="/statement">
                    Statement Fetcher
                  </SidebarItem>
                  <SidebarItem to={shit} href={shit}>
                    Shit Odds
                  </SidebarItem>

                  <SidebarItem href={repo} to={repo}>
                    Github repo
                  </SidebarItem>
                </SidebarSection>
              </SidebarHeader>
              <SidebarBody>
                <SidebarSection>
                  <SidebarHeading>Sports</SidebarHeading>
                  {json.data.categories.map((c) => (
                    <SidebarItem to={c.url} href={c.url} key={c.id}>
                      <p className="text-xs">{c.name}</p>
                    </SidebarItem>
                  ))}
                </SidebarSection>
              </SidebarBody>
            </Sidebar>
          }
        >
          {children}
        </SidebarLayout>
      </body>
    </html>
  );
}
